---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: echoapp-prod
  chart:
    git: git@github.com:OmerBM1998/DevBC-echo
    path: charts/echoapp
    ref: main
  values:
    image:
      repository: eu.gcr.io/develeapecho/echo
      tag: 1.0.2
    replicaCount: 3
