---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echoapp-rc
  chart:
    git: git@github.com:OmerBM1998/DevBC-echo
    path: charts/echoapp
    ref: main
  values:
    image:
      repository: eu.gcr.io/develeapecho/echo
      tag: stg-tvamtnte
    replicaCount: 2
