apiVersion: v1
kind: Service
metadata:
  name: {{ include "echoapp.fullname" . }}-{{ .Values.service.name }}
  labels:
    {{- include "echoapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "echoapp.selectorLabels" . | nindent 4 }}
